import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {Flex, Space} from "antd";
import React from "react";
import {SiFacebook, SiInstagram} from "react-icons/si";
import dayjs from "dayjs";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <header className='w-screen py-[12px] flex justify-center'>
            <div className='flex justify-between items-center w-3/5'>
                Logo
                <Space size={20}>
                    <Link href='/about-us'>
                        <div className='hover:text-[#d57c3d] hover:no-underline font-light py-[13px] px-[18px] text-black cursor-pointer'>About us</div>
                    </Link>
                    <Link href='/about-us'>
                        <div className='hover:text-[#d57c3d] hover:no-underline font-light py-[13px] px-[18px] text-black cursor-pointer'>About us</div>
                    </Link>
                    <Link href='/about-us'>
                        <div className='hover:text-[#d57c3d] hover:no-underline font-light py-[13px] px-[18px] text-black cursor-pointer'>About us</div>
                    </Link>
                    <Link href='/about-us'>
                        <div className='hover:text-[#d57c3d] hover:no-underline font-light py-[13px] px-[18px] text-black cursor-pointer'>About us</div>
                    </Link>
                </Space>
                <div className='bg-[#d57c3d] hover:bg-[#d57c3d80] font-light py-[13px] px-[18px] text-white text-base rounded-sm cursor-pointer'>Explore Now</div>
            </div>
        </header>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        </body>
        <footer className='w-screen bg-[#f3f4f6] py-[80px] flex justify-center'>
            <div className='w-3/5 flex flex-col justify-center items-center gap-[20px]'>
                <div className='w-full flex justify-between items-center'>
                    Logo
                    <Space size={20}>
                        <Link href='/about-us'>
                            <Button variant='link'
                                    className='hover:text-[#d57c3d] hover:no-underline font-light text-sm'>About
                                us</Button>
                        </Link>
                        <Link href='/about-us'>
                            <Button variant='link'
                                    className='hover:text-[#d57c3d] hover:no-underline font-light text-sm'>About
                                us</Button>
                        </Link>
                        <Link href='/about-us'>
                            <Button variant='link'
                                    className='hover:text-[#d57c3d] hover:no-underline font-light text-sm'>About
                                us</Button>
                        </Link>
                        <Link href='/about-us'>
                            <Button variant='link'
                                    className='hover:text-[#d57c3d] hover:no-underline font-light text-sm'>About
                                us</Button>
                        </Link>
                    </Space>
                    <Space>
                        <SiFacebook/>
                        <SiInstagram/>
                    </Space>
                </div>
                <div className='h-[1px] w-full bg-slate-900'/>
                <div className='mt-[40px] w-full flex gap-[20px]'>
                    <div className='w-1/2 flex justify-end items-center'>
                        <span className='font-light text-sm'>© {dayjs().year()} Name. All rights reserved.</span>
                    </div>
                    <div className='w-1/2 flex gap-[20px]'>
                        <span className='hover:text-[#d57c3d] hover:no-underline font-light text-sm cursor-pointer'>Terms and Conditions</span>
                        <span className='hover:text-[#d57c3d] hover:no-underline font-light text-sm cursor-pointer'>Privacy Policy</span>
                    </div>
                </div>
            </div>
        </footer>
        </html>
    );
}
